[package]
name = "linode"
version = "0.1.0"
edition = "2021"

[dependencies]
mongodb = "2.3.0"
tokio = { version = "1", features = ["full"]  }
futures = "0.3"
serde = "1"
chrono = "0.4"
twilio-async = { version = "0.5" }
